CREATE DATABASE IF NOT EXISTS `48HOURS`;

USE 48HOURS;

DROP TABLE IF EXISTS UTILISATEUR;

CREATE TABLE UTILISATEUR(
    idUtilisateur INT PRIMARY KEY AUTO_INCREMENT,
    nom VARCHAR(50) NOT NULL,
    prenom VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    motDePasse VARCHAR(50) NOT NULL,
    niveau INT
);